version: '3'

networks:
  internal:
    driver: bridge

services:
  msa-write:
    build: msa-write
    container_name: msawrite
    networks:
      - internal
    ports: 
      - 3000:3000
  msa-read:
    build: msa-read
    container_name: msaread
    networks:
      - internal
    ports:
      - 3001:3001
  gateway:
    build: gateway
    container_name: gateway
    networks:
      - internal
    depends_on:
      - msa-write
      - msa-read
    ports:
      - 8080:8080
